# ClusterRegistration Sample
# This example shows how to join a cluster to KubeVela using individual connection parameters
# and a Secret for credentials

# Step 1: Create a Secret containing the spoke cluster's credentials
# The secret must contain either:
#   - "client-certificate-data" + "client-key-data" (for X509 cert auth)
#   - "token" (for bearer token / ServiceAccount auth)
---
apiVersion: v1
kind: Secret
metadata:
  name: spoke-1-credentials
  namespace: vela-system
type: Opaque
data:
  # These are base64-encoded client certificate and key from the spoke cluster
  client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJZlYydUlRVGZsZnN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN4TWpRNU1UUXpNQjRYRFRJMk1ESXhOakV6TXprd00xb1hEVEkzTURJeApOakV6TXprd00xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQWkEyZUJZKzdTMjFHUlgKVys1V3RxUGs5dHVCc3o5cC9hblY2M3NESVhEc3dEYmg5ZjFlNTRQMTdRQ0Y5cXJSWmxvVU1SQ2RWVWxMQU1pTwpEK2dLWm5TalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXVKOVlqWHJvNWVRSXJmWVBIY2JlNE1iNkpsekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBbDFicWtoc1JiWlNxbXBKYTkyVEFaR1FMS2ladkRmNlc3VkFIc3BjNHlHQUloQU5XQ0V4NE1PSjJYMTBkQgo0OWs0OEZXZHJBTEp3ZzVkemNod1QwaTNJV2dLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpFeU5Ea3hORE13SGhjTk1qWXdNakUyTVRNek9UQXpXaGNOTXpZd01qRTBNVE16T1RBegpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpFeU5Ea3hORE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOW5vZ1lOMTZTUkN2eDY3eXRyaTVRbXBkWUJycVIxRkJnUWJHVmQyb3oKL1NjVTJUVFQ3Z2pVWFlRUWQ0NWUxL0wyd1FHdjh0MmlHbVBPdDV1VXpadUVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUxpZldJMTY2T1hrQ0szMkR4M0czCnVERytpWmN3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVzFpQzRMNExUaGR5Ykpqa1RhK2wrcEpqL2J3VTdnRW4KZGV2K3ZKNE14alVDSUJNUmxvQUh4WnFxbmw1bEhOUUNvZnNQM3JPcXA2Y3NkSy9JT3NWcGhWa1oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtoMVgvbTlmRFhjdzI1QS9SLzRpSjhQZXVjVTdSbUw2eHN1ZGkvLy9ZTlJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOWtEWjRGajd0TGJVWkZkYjdsYTJvK1QyMjRHelAybjlxZFhyZXdNaGNPekFOdUgxL1Y3bgpnL1h0QUlYMnF0Rm1XaFF4RUoxVlNVc0F5STRQNkFwbWRBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

# Step 2: Create the ClusterRegistration resource
---
apiVersion: core.oam.dev/v1beta1
kind: ClusterRegistration
metadata:
  name: my-remote-cluster
  namespace: vela-system
spec:
  # clusterName is the name the cluster will be registered as
  # If empty, defaults to metadata.name
  clusterName: spoke-1

  # alias is a human-readable name for the cluster (optional)
  alias: "spoke-1"

  # server is the API server endpoint of the spoke cluster
  server: https://192.168.29.196:54430

  # insecureSkipTLSVerify skips TLS verification (not recommended for production)
  insecureSkipTLSVerify: true

  # caData is the base64-encoded CA certificate (use this instead of insecureSkipTLSVerify for production)
  # caData: "LS0tLS1CRUdJTi..."

  # credentialSecret references the Secret containing auth credentials
  credentialSecret:
    name: spoke-1-credentials

  # createNamespace specifies the namespace to create in the managed cluster
  # Defaults to "vela-system"
  createNamespace: "vela-system"

  # labels are custom labels to add to the cluster for selection
  labels:
    env: production
    region: us-west-2