# ClusterRegistration Sample
# This example shows how to join a cluster to KubeVela by creating a ClusterRegistration resource
# with an inline kubeconfig

apiVersion: core.oam.dev/v1beta1
kind: ClusterRegistration
metadata:
  name: my-remote-cluster
  namespace: vela-system
spec:
  # clusterName is the name the cluster will be registered as
  # If empty, defaults to metadata.name
  clusterName: spoke-1

  # alias is a human-readable name for the cluster (optional)
  alias: "spoke-1"

  # kubeconfig is the complete kubeconfig content for the cluster to join
  # Simply copy-paste your kubeconfig file content here
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://192.168.29.196:64627
      name: k3d-spoke
    contexts:
    - context:
        cluster: k3d-spoke
        user: admin@k3d-spoke
      name: k3d-spoke
    current-context: k3d-spoke
    kind: Config
    preferences: {}
    users:
    - name: admin@k3d-spoke
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJWld1T2xFR0JubUV3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TmpJeU1qQTNNQjRYRFRJMk1ESXdPVEEzTXpBd04xb1hEVEkzTURJdwpPVEEzTXpBd04xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCdmhTQ1J1bkp3QVpVWmoKNmRVb1BVMzVEWWNRb3hrdUw0M2M5NWNIeE1zR0VOWHpZVWNyT2srdTNHQmVBcG9ZaXliUnFxK3NFQmJHbHpYNgpYZkE3QTNXalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVHdEK1lSbHNnczduUUNuWXlKWUs2bmgvSERZekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTRubHV5RENLbFRZV0EzQWtNc0h2MlkvL01YY01NY3BnWnNzVzRvbEhyYUlDSVFETWNuOFN0ZW9DMzNFaApLNVhHa0puRXlIV3lodWkvdEUzVXVPQngxanErZVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM056QTJNakl5TURjd0hoY05Nall3TWpBNU1EY3pNREEzV2hjTk16WXdNakEzTURjek1EQTMKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM056QTJNakl5TURjd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVDd5K0ZVcEQzYlhtcFRQb1lPQ0hnd2Y4bWkwc3NTSlFoQWVUK3lPdS9wClRwNmxvUksrTnhHSWp4R21VU3JOSDY0anh2bUhnK1NkRkt6czBnajM0eUJrbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU4QS9tRVpiSUxPNTBBcDJNaVdDdQpwNGZ4dzJNd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ011UjJBczB6dDExWjFDVm0zc3diaEpPdjh0UlNtMm0vClNUWlRZQTNOL3A0Q0lEUWhwZHM5a0UvZUZGTlNjMHFYUVlvejNjS1g5Z2t0ODF5U0xNWW85S0o1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxvNHEvZTZzenVGN1VlckpHTnFGSng5QmhBOHU5ekhFQWhTMnp4QlhzOHlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRytGSUpHNmNuQUJsUm1QcDFTZzlUZmtOaHhDakdTNHZqZHozbHdmRXl3WVExZk5oUnlzNgpUNjdjWUY0Q21oaUxKdEdxcjZ3UUZzYVhOZnBkOERzRGRRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=


  # createNamespace specifies the namespace to create in the managed cluster
  # Defaults to "vela-system"
  createNamespace: "vela-system"

  # labels are custom labels to add to the cluster for selection
  labels:
    env: production
    region: us-west-2